/*  Message-number definitions derived from "ELWTD.MSG"  */

#define TDICEKEY    1
#define TDICEMSV    3
#define MMENU       5
#define SMENU       6
#define LOGIN       7
#define DICEINS     8
#define ROLL        9
#define CORRECT    10
#define WRONG      11
#define ABORT      12
#define BADGUESS   13
#define ENDGAME    14
#define LEAVE      15
#define NOGOOD     16
#define WINNING    17
#define TOPTEN     18
#define TOPS       19
#define NOSCORES   20
#define NOHIGHS    21
#define NOTLIV     22
#define DIE1       23
#define DIE2       24
#define DIE3       25
#define DIE4       26
#define DIE5       27
#define DIE6       28
